using System.Net.Http.Headers;
using Microsoft.Rest;

namespace Albelli.MiscUtils.Lib
{
    public class UnauthorizedTokenProvider : ITokenProvider
    {
        private const string UnauthorizedToken = "eyJ0eXAiOiJKV1QiLCJhbGfciOiJSUdsfeUIsIng1dCI6IkZLNHRwMUVMRVpPM0J4RERFTFFxSXhFaEV0WSIsImtpZCI6IkZLNHRwMUVMRVpPM0J4RERFTFFxSXhFaEV0WSJ9.eyJpc3MiOiJodHRwczovL3QtZHRhcC5sb2dpbi5hbGJlbGxpLmNvbS92Mi8iLCJhdWQiOiJodHRwczovL3QtZHRhcC5sb2dpbi5hbGJlbGxpLmNvbS92Mi9yZXNvdXJjZXMiLCJleHAiOjE1ODE1MjExNzMsIm5iZiI6MTU4MTUxNzU3MywiY2xpZW50X2lkIjoiZDNmOTc0YmYzZGVkNGZjNzlkYTZiNDI5NTljNzA2MzMiLCJzY29wZSI6Im9yZGVycHJvbWlzZS5yZWFkIiwic3ViIjoiZjc4ZmU0ODg5MmI0NDFkOGFjZTk0Zjk2M2UzMjVlZjAiLCJhdXRoX3RpbWUiOjE1ODE1MTc1NzMsImlkcCI6ImFsYmVsbGlkb21haW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL2F1dGhlbnRpY2F0aW9ubWV0aG9kIjoiZG9tYWluIiwiZW1haWwiOiJkdnV1cmJvb21AYWxiZWxsaS5uZXQiLCJpZHBfdHlwZSI6ImFsYmVsbGlkb21haW4iLCJpZHBfc3ViIjoiVXI1OXVfeUZsR0FxTVFnLWMxZXZLRVFhVVAzakxJajZLOTFXYUl3N3d6MCIsImFtciI6WyJleHRlcm5hbCJdfQ.pfoC7eNreZXTUpdS_gnAJnX4CYbwFnw6V8XP_ZKbxbFgFTB_wgcviIt09tIlma6zzg43kc5hjhvbPyEPDnixdwDWuWtXtRID_ag8BE0gwG4xrAfqpDaawAS5Jun1i0Iz65l4tQXlpV_pbwDWDJLM-HVrRdzIkRy7E43PoKPWhkaf8CwWJ6b8SXtaRpDbjTDbZxa2e9uzjgxhliOdIuddSdHzdHLGrSGAaHfwWMvdhQcOLlCWCq7vtLGuQGyrYVsNJ72ZhAfofE45NKOkDkyt2P8h8-Xj09P0GDgKXQpr6BPGcMu9xeo79yywHDesvH85ZyRs9mtwQJG6XWgyGFTq3g";

        public Task<AuthenticationHeaderValue> GetAuthenticationHeaderAsync(CancellationToken cancellationToken)
        {
            return Task.FromResult(new AuthenticationHeaderValue("Bearer", UnauthorizedToken));
        }
    }
}
