@echo off
SET CENTRAL_LOG=%~1
SET API_URL=%~2
SET API_URL2=%~3
SET AUTH_TOKEN=%~4
SET API_URL_PROD=%~4
SET API_URL2_PROD=%~5
SET AUTH_TOKEN_PROD=%~7

REM Var(s)
SET LOG_PATH=%LOGS_DIR%\PCT10481ReplayCPDs.log
SET ERR_LOG_PATH=%LOGS_DIR%\PCT10481ReplayCPDs.err.log
..\bin\Debug\net6.0\Albelli.MiscUtils.CLI.exe PCT10481ReplayCPDs "%CENTRAL_LOG%" "%API_URL%" "%AUTH_TOKEN%" "%API_URL2%" "%AUTH_TOKEN%" "%API_URL_PROD%" "%AUTH_TOKEN_PROD%" "%API_URL2_PROD%" "%AUTH_TOKEN_PROD%" 1> "%LOG_PATH%" 2> "%ERR_LOG_PATH%"