@echo off
SET PLANTS_PRODUCT_TYPES_PATH=%~1
SET MYFACTORY_API_URL=%~2
SET PHYS_PROD_CAT_API_URL=%~3
SET PKG_CALC_API_URL=%~4
SET MYFACTORY_API_TOKEN=%~5
SET PHYS_PROD_CAT_API_TOKEN=%~6
SET PKG_CALC_API_TOKEN=%~7
SET SAVE_AS_PFX=%~8

REM Var(s)
SET LOG_PATH=%SAVE_AS_PFX%.PCT11312_Export.log
SET LOG_ERROR_PATH=%SAVE_AS_PFX%.PCT11312_Export.Error.log
..\bin\Debug\net6.0\Albelli.MiscUtils.CLI.exe PCT11312_Export "%PLANTS_PRODUCT_TYPES_PATH%" "%MYFACTORY_API_URL%" "%PHYS_PROD_CAT_API_URL%" "%PKG_CALC_API_URL%" "%MYFACTORY_API_TOKEN%" "%PHYS_PROD_CAT_API_TOKEN%" "%PKG_CALC_API_TOKEN%" "%SAVE_AS_PFX%" %9 1> "%LOG_PATH%" 2> "%LOG_ERROR_PATH%"