@echo off
SET SRC_XLS_PATH=%~1
SET SRC_SHEET_NM=%~2
SET API_URL=%~3
SET API_TOKEN=%~4
SET API_URL_T=%~5
SET API_TOKEN_T=%~6
SET MATRIX_PROD=%~7
SET ZONES_PROD=%~8
SET MATRIX_UAT=%~9

REM Var(s)
SET LOG_PATH=%SRC_XLS_PATH%.PCT9944BulkRevalidate.log
..\bin\Debug\net6.0\Albelli.MiscUtils.CLI.exe PCT9944BulkRevalidate "%SRC_XLS_PATH%" "%SRC_SHEET_NM%" "%API_URL%"  "%API_TOKEN%" "%API_URL_T%"  "%API_TOKEN_T%" "%MATRIX_PROD%" "%ZONES_PROD%" "%MATRIX_UAT%" -NoLogo 1> "%LOG_PATH%" 2>&1